# Definição de variáveis manuais (Substitutions)
# É boa prática usar variáveis com "_" para diferenciar das automáticas do Google
substitutions:
  _REGION: 'us-central1' # Altere para sua região (ex: southamerica-east1)
  _AR_REPO_NAME: 'meu-repositorio-docker' # Nome do repositório criado no Artifact Registry

steps:
  # 1. Build da imagem Docker
  # "Virar artefato" começa aqui: transformamos o código em uma imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/meu-job-python:latest', 
      '.'
    ]

  # 2. Push da imagem para o Artifact Registry
  # AQUI O ARTEFATO É SALVO: O comando push envia a imagem criada para o Google Cloud
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/meu-job-python:latest'
    ]

  # 3. (Opcional) Atualizar/Criar o Cloud Run Job
  # Isso garante que o Job use sempre a última imagem (artefato) criada
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'jobs', 'update', 'meu-job-python-job',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/meu-job-python:latest',
      '--region', '${_REGION}',
      '--set-env-vars', 'AMBIENTE=Producao'
    ]

# Define onde a imagem final ficará disponível
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/meu-job-python:latest'

# CORREÇÃO DO ERRO (Tentativa 2 - Mais Robusta):
# Usa um bucket regional próprio do usuário para os logs.
# Isso resolve o problema de permissão da Service Account sem desativar os logs.
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
